FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

COPY src/database/prisma/schema.prisma ./src/database/prisma/
RUN npx prisma generate

EXPOSE 3001

ENTRYPOINT [ "sh", "-c" ]

CMD [ "npx prisma migrate dev --name dev && npm run start:dev" ]